dataset_path: lotsoliu/EgoTaskQA  
dataset_kwargs:  
  token: True  
  # cache_dir: egotaskqa  
task: "egotaskqa"  
test_split: test  
output_type: generate_until  
doc_to_text: !function utils.egotaskqa_doc_to_text  
doc_to_visual: !function utils.egotaskqa_doc_to_visual
# doc_to_messages: !function utils.egotaskqa_doc_to_messages  
doc_to_target: "answer"  
generation_kwargs:  
  max_new_tokens: 500
  temperature: 0  
  top_p: 1.0  
  num_beams: 1  
  do_sample: false  
process_results: !function utils.egotaskqa_process_results  
metric_list:  
  - metric: acc  
    aggregation: !function utils.egotaskqa_aggregate_accuracy  
    higher_is_better: true  
metadata:  
  - version: 0.0