dataset_path: json
dataset_kwargs:  
  data_files: 
  - /home/alex/datasets/crpe/CRPE/crpe_exist.jsonl  
  - /home/alex/datasets/crpe/CRPE/crpe_relation.jsonl  
task:  crpe
test_split: train
output_type: generate_until  
doc_to_text: !function utils.crpe_doc_to_text  
doc_to_messages: !function utils.crpe_doc_to_messages  # v0.4 推荐接口  
doc_to_target: !function utils.crpe_doc_to_target  
generation_kwargs:  
  temperature: 0  
  do_sample: false  
process_results: !function utils.crpe_process_results  
metric_list:  
  - metric: acc  
    aggregation: !function utils.crpe_aggregate_accuracy  
    higher_is_better: true  
lmms_eval_specific_kwargs:  
  default:  
    pre_prompt: ""  
    post_prompt: ""  
metadata:  
  - version: 0.0