dataset_path: ellisbrown/OpenEQA  
dataset_kwargs:  
  token: True  
  cache_dir: openeqa  
  video: True  
task: openeqa_hm3d  # 唯一的任务名称  
test_split: test  
process_docs: !function utils.openeqa_hm3d_process_docs  # 过滤 hm3d 数据  
doc_to_visual: !function utils.openeqa_doc_to_visual  
doc_to_text: !function utils.openeqa_doc_to_text  
doc_to_target: "answer"  
generation_kwargs:  
  max_new_tokens: 500 
  temperature: 0  
  top_p: 1.0  
  num_beams: 1  
  do_sample: false  
process_results: !function utils.openeqa_process_results  
metric_list:  
  - metric: acc  
    aggregation: !function utils.openeqa_aggregate_accuracy 
    higher_is_better: true  
metadata:  
  - version: 0.0