group: refspatial
task:  
  - refspatial_location
  - refspatial_placement
  - refspatial_unseen
aggregate_metric_list:  
  - metric: acc  
    aggregation: mean  
    weight_by_size: true  
metadata:  
  version: 0.0