dataset_path: /home/unitree/桌面/datasets/RefSpatial/refspatial
dataset_kwargs:    
  load_from_disk: True
task: refspatial_placement
group: refspatial
test_split: placement 
output_type: generate_until  
doc_to_text: !function utils.refspatial_doc_to_text  
doc_to_messages: !function utils.refspatial_doc_to_messages 
doc_to_target: !function utils.refspatial_doc_to_target
process_results: !function utils.refspatial_process_results 

lmms_eval_specific_kwargs:  
  pre_prompt: ""  
  post_prompt: "Output the point coordinates in JSON format.\n For example:[{\"point_2d\": [x, y], \"label\": \"point_1\"}]"
  
generation_kwargs:  
  max_new_tokens: 1000
  temperature: 0  
  do_sample: false  
metric_list:  
  - metric: acc  
    aggregation: mean
    higher_is_better: true  
metadata:  
  - version: 0.0