dataset_path: FlagEval/ERQA  
# dataset_path: /home/unitree/Qwen_test/dataset_download/erqa
# dataset_kwargs:  
#   load_from_disk: True
task: "erqa"  
test_split: test  
output_type: generate_until  
doc_to_visual: !function utils.erqa_doc_to_visual  
doc_to_text: !function utils.erqa_doc_to_text  
doc_to_messages: !function utils.erqa_doc_to_messages  # v0.4 推荐接口  
doc_to_target: !function utils.erqa_doc_to_target  
generation_kwargs:  
  temperature: 0  
  top_p: 1.0  
  num_beams: 1  
  do_sample: false  
process_results: !function utils.erqa_process_results  
metric_list:  
  - metric: acc  
    aggregation: !function utils.erqa_aggregate_accuracy  
    higher_is_better: true  
lmms_eval_specific_kwargs:  
  default:  
    pre_prompt: ""  
    post_prompt: ""  
metadata:  
  - version: 0.0