# dataset_path: FlagEval/ERQA  
dataset_path: /home/jensen/remote_jensen/huangjianxin/vlm_benchmark/Where2Place
# dataset_kwargs:  
#   load_from_disk: True
task: "where2place"  
test_split: test  
output_type: generate_until  
# doc_to_visual: !function utils.where2place_doc_to_visual  
doc_to_text: !function utils.where2place_doc_to_text  
doc_to_messages: !function utils.where2place_doc_to_messages  # v0.4 推荐接口  
doc_to_target: !function utils.where2place_doc_to_target  
generation_kwargs:  
  temperature: 0.5
  do_sample: true
  max_new_tokens: 1024
process_results: !function utils.where2place_process_results  
metric_list:  
  - metric: acc  
    aggregation: !function utils.where2place_aggregate_results  
    higher_is_better: true  
lmms_eval_specific_kwargs:  
  default:  
    pre_prompt: ""  
    post_prompt: "Your answer should be formatted as a list of tuples, i.e. [(x1, y1), ...], where each tuple contains the x and y coordinates of a point satisfying the conditions above."  
metadata:  
  - version: 0.0