dataset_path: nyu-visionx/CV-Bench
# dataset_path: /home/unitree/Qwen_test/dataset_download/erqa
# dataset_kwargs:  
#   load_from_disk: True
task: "cvbench"  
test_split: test  
output_type: generate_until  
doc_to_text: !function utils.cvbench_doc_to_text  
doc_to_messages: !function utils.cvbench_doc_to_messages  # v0.4 推荐接口  
doc_to_target: !function utils.cvbench_doc_to_target  
generation_kwargs:  
  temperature: 0  
  do_sample: false  
process_results: !function utils.cvbench_process_results  
metric_list:  
  - metric: acc  
    aggregation: !function utils.cvbench_aggregate_accuracy  
    higher_is_better: true  
lmms_eval_specific_kwargs:  
  default:  
    pre_prompt: ""  
    post_prompt: "Just output the answer you select ,For example:(A) or (B) or anothor option."  
metadata:  
  - version: 0.0