dataset_path: lmms_eval/tasks/omni3d/omni3d_dataset_builder.py  
dataset_kwargs:  
  data_files:   
    test: "/home/jensen/remote_jensen/huangjianxin/vlm_benchmark/Omni3D/arkitscenes/*.annotations.json"  # 指定本地 JSON 文件路径  
task: omni3d_arkitscenes
test_split: test  
output_type: generate_until  
  
doc_to_visual: !function utils.omni3d_doc_to_visual  
doc_to_text: !function utils.omni3d_doc_to_text  
doc_to_target: !function utils.omni3d_doc_to_target  
  
generation_kwargs:  
  max_new_tokens: 10000
  temperature: 0.7  
  do_sample: true  
  
process_results: !function utils.omni3d_process_results  
  
metric_list:  
  - metric: ap15  
    aggregation: !function utils.omni3d_aggregate_results  
    higher_is_better: true
  
metadata:  
  version: 0.0